name: ktlint

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - matser
  workflow_dispatch:

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "ktlint"
        uses: "block42-blockchain-company/ktlint-action@master"